language: php
php:
  - '5.6'
  - '7.0'
  - hhvm

sudo: true

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  - pecl channel-update pecl.php.net
  - (CFLAGS="-O1 -g3 -fno-strict-aliasing"; pecl install yaml < /dev/null &)
    
