language: php
php:
  - 7.0

sudo:
  false 

before_script:
  - yes '' | pecl install yaml
  - composer install 


after_success:
  - ./vendor/bin/coveralls -v --exclude-no-stmt
  - bash <(curl -s https://codecov.io/bash)
    
