language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

sudo: false    

script:
 - mkdir -p build/logs
 - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
