language: php
php:
  - 7.0.0

sudo:
  false 

before_script:
  - printf "\n" | pecl install yaml-2.0.0
  - composer install 
  - phpunit --version
  - composer global require phpunit/phpunit ^6.0
  - phpunit --version
    


after_success:
  - ./vendor/bin/coveralls -v --exclude-no-stmt
  - bash <(curl -s https://codecov.io/bash)
    
