language: php
php:
  - 5.6.25
  - 7.0
  - hhvm

sudo:
  false 

before_script:
  - echo "\n" | pecl install yaml
  - echo "extension=yaml.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --dev
