language: php
php:
  - 7.0

sudo:
  false 

before_script:
  - printf "\n" | pecl install yaml-2.0.0
  - composer install 
  - php -i|grep yaml


after_success:
  - ./vendor/bin/coveralls -v --exclude-no-stmt
  - bash <(curl -s https://codecov.io/bash)
    
