language: php
php:
  - 5.6.25

sudo:
  false 

before_script:
  - echo "\n" | pecl install yaml
  - echo "extension=yaml.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --dev

after_success:
  - ./vendor/bin/coveralls -v --exclude-no-stmt
  - bash <(curl -s https://codecov.io/bash)
    
